### ISSUE TITLE
ArrayController binding to all models does not get notified of a newly created model

### ISSUE THREAD

**Issue by hperl** [getoutreach/epf#44]
I have an `Em.ArrayController` with the model property bound in a route like this:

``` javascript
  model: function() {
    return this.session.query('foo');
  }
```

Now, to create a new `Foo` I have the following action on the `App.FoosController`:

``` javascript
App.FoosController = Ember.ArrayController.extend({
  newFoo: function() {
    this.session.create(App.Foo, {name: "New Foo"});
    this.session.flush();
  }
});
```

However, `App.FoosController`'s `model` property does not change (but it does using Ember Data). For this to work, I need to manually add the object to the controller's model (e.g. `this.get('model').addObject(foo)`).

Is it possible to do this automatically?

**Comment by jasonkriss** [comment]
The issue here is that `this.session.query('foo')` does not return a live array like ED's `find()` and `all()`. When you call query, it is simply a returning a snapshot of the foo records that exist on the server at that time and it will not be updated automatically. This functionality could probably be added pretty easily but I think it may have been a conscious decision to leave it out. I don't want to put words in his mouth but I think @ghempton has said that he views it as somewhat of an anti-pattern.

**Comment by ghempton** [comment]
@jasonkriss is right that collections that result from queries are not live updating right now (relationships do). The issue here is that `session.query` just sends down arbitrary parameters down to the server and has no knowledge of how the server actually does the filtering. I would ultimately like to come up with a solution to this, but for the time being the correct thing to do is to manually add to the collection.

As an aside, ED is able to do this for `findAll` because it is a special cased query of _all_ records of a type. I think that this particular behavior is an anti-pattern since in a real application you are almost always filtering/scoping all results from the server.

**Comment by hperl** [comment]
Thanks for the clarification. And I see that the query result could in some cases not be simply done on the client side, as it may be of a complex form involving full text search, pagination etc.
